// Made-up data for tests. Same shapes as a real setup (cards with MSI, a card plan with interest,
// loans, a phone plan, weekly pay) with round numbers that are easy to check by hand.
import { seedToFinanceData, type SeedFile } from "../lib/seed";

export const TODAY = "2026-10-01";

export const FIXTURE: SeedFile = {
  accounts: [
    {
      key: "payroll",
      name: "Payroll debit",
      institution: "Bank 1",
      type: "debit",
      balance: 500,
      credit_limit: null,
      statement_day: null,
      payment_due_days: null,
      notes: "",
    },
    {
      // 10,000 owed, of which 5,100 is MSI -> 4,900 to pay in full, due Oct 27
      key: "card_a",
      name: "Card A",
      institution: "Bank 1",
      type: "credit",
      balance: 10000,
      credit_limit: null,
      statement_day: 7,
      payment_due_days: 20,
      notes: "",
    },
    {
      // Current statement already paid; 8,000 owed, 4,900 of it in the plan -> 3,100, due Nov 4
      key: "card_b",
      name: "Card B",
      institution: "Bank 2",
      type: "credit",
      balance: 8000,
      credit_limit: null,
      statement_day: 15,
      payment_due_days: 20,
      next_due_date: "2026-11-04",
      notes: "",
    },
    {
      key: "card_c",
      name: "Card C",
      institution: "Bank 3",
      type: "credit",
      balance: 2000,
      credit_limit: null,
      statement_day: null,
      payment_due_days: 20,
      notes: "",
    },
    {
      key: "wallet",
      name: "Wallet",
      institution: "Fintech",
      type: "wallet",
      balance: 0,
      credit_limit: null,
      statement_day: null,
      payment_due_days: null,
      notes: "",
    },
    {
      key: "vouchers",
      name: "Vouchers",
      institution: "Employer",
      type: "voucher",
      balance: 300,
      credit_limit: null,
      statement_day: null,
      payment_due_days: null,
      notes: "",
    },
  ],
  plans: [
    {
      name: "Card B installments",
      account: "card_b",
      kind: "with_interest",
      original_amount: 6300,
      payment_amount: 820,
      capital_per_payment: 700,
      total_payments: 9,
      payments_made: 2,
      next_payment_date: "2026-11-04",
      notes: "",
    },
    {
      name: "Card A 15 MSI",
      account: "card_a",
      kind: "msi",
      original_amount: 3000,
      payment_amount: 200,
      capital_per_payment: null,
      total_payments: 15,
      payments_made: 0,
      next_payment_date: "2026-10-27",
      notes: "",
    },
    {
      name: "Card A 3 MSI",
      account: "card_a",
      kind: "msi",
      original_amount: 900,
      payment_amount: 300,
      capital_per_payment: null,
      total_payments: 3,
      payments_made: 0,
      next_payment_date: "2026-10-27",
      notes: "",
    },
    {
      name: "Card A 12 MSI",
      account: "card_a",
      kind: "msi",
      original_amount: 1200,
      payment_amount: 100,
      capital_per_payment: null,
      total_payments: 12,
      payments_made: 0,
      next_payment_date: "2026-10-27",
      notes: "",
    },
    {
      name: "Loan 1",
      account: "wallet",
      kind: "loan",
      original_amount: 12000,
      payment_amount: 1700,
      capital_per_payment: 1333.33,
      total_payments: 9,
      payments_made: 3,
      next_payment_date: "2026-11-01",
      notes: "",
    },
    {
      name: "Loan 2",
      account: "wallet",
      kind: "loan",
      original_amount: 3000,
      payment_amount: 600,
      capital_per_payment: 500,
      total_payments: 6,
      payments_made: 3,
      next_payment_date: "2026-11-01",
      notes: "",
    },
    {
      name: "Phone",
      kind: "device",
      original_amount: 24000,
      payment_amount: 1000,
      capital_per_payment: null,
      total_payments: 24,
      payments_made: 0,
      next_payment_date: "2026-10-26",
      notes: "",
    },
  ],
  bills: [
    { name: "Phone insurance", amount: 200, day_of_month: 26, category: "phone_internet", is_estimate: false, notes: "" },
    { name: "Streaming", amount: 150, day_of_month: 15, category: "subscriptions", is_estimate: true, notes: "" },
    {
      name: "Gym",
      amount: 500,
      day_of_month: 1,
      category: "health",
      is_estimate: false,
      notes: "CONFIRM: day of the month.",
    },
  ],
  incomes: [
    {
      name: "Salary",
      account: "payroll",
      amount: 3000,
      frequency: "weekly",
      anchor_date: "2026-10-02",
      restricted_to: null,
      notes: "",
    },
    {
      name: "Vouchers",
      account: "vouchers",
      amount: 250,
      frequency: "weekly",
      anchor_date: "2026-10-02",
      restricted_to: "food",
      notes: "",
    },
  ],
  profile: "Test user.",
};

export const fixtureData = () => seedToFinanceData(FIXTURE);
